---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Adriana Banchs, amb8722

#### Introduction 

The data sets used for this project are the World Happiness Report and Socio-Economic Country Profiles. Both of the data are from 2017, so the values can be more easily compared. The World Happiness Report contains data measuring happiness in many different countries, using happiness scores based on different factors, as well as rankings of happiness among the countries. The Socio-Economic Country Profiles data set contains different measures for countries relating to the economy, health, employment, demographics, and more. These two data sets are interesting to compare because different factors, such as GDP and employment rates can be compared to the happiness scores of different countries to see how they are related, and which factors have the greatest effect on happiness. Some things that are expected are that countries with healthier populations, smaller unemployment rates, and a higher GDP would have higher happiness scores. 

```{R}
library(tidyverse)
library(knitr)
happy <- read_csv("happy.csv")
profile <- read_csv("profile.csv")
```

#### Tidying: Reshaping

If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.

```{R}
#untidying
untidy_profile <- profile %>% pivot_wider(names_from="Region", values_from="country") %>% 
  select(49:70, everything())
untidy_profile %>% head()

untidy_happy <- happy %>% pivot_wider(names_from="Happiness.Rank", values_from="Country") %>% 
  select(11:165, everything())
untidy_happy %>% head()

#retidying
untidy_profile %>% pivot_longer(1:22, names_to="Region", values_to="country") %>%
  select(country, Region, everything()) %>% na.omit()
untidy_happy %>% pivot_longer(1:155, names_to="Happiness.Rank", values_to="country") %>%
  select(country, Happiness.Rank, everything()) %>% na.omit()

profile %>% separate(`Labour force participation (female/male pop. %)`, into=c("Laborforce_participation_women_%","Laborforce_participation_men_%"), sep="/") %>%
  separate(`Life expectancy at birth (females/males, years)`, into=c("Lifeexpectancy_females_yrs", "Lifeexpectancy_males_yrs"), sep="/") %>% separate(`Population age distribution (0-14 / 60+ years, %)`, into=c("Pop_age_dist_0-14yrs_%", "Pop_age_dist_60+yrs_%")) %>% separate(`Pop. using improved drinking water (urban/rural, %)`, into=c("Pop_improveddrinkingwater_urban_%", "Pop_improveddrinkingwater_rural_%")) -> profile
profile %>% head
```

Since both data sets were already pretty tidy, the profile data set was first untidied by placing each region name as a column, with the countries as the values. This created many more columns with a lot of NA values, and the variable "Region" was in the column instead of as a variable in the row. This makes it really hard to compare countries of different regions. The profile data set was then tidied by pivoting longer and creating a Region column with all of the regions as values. In the happy data set, it was pivoted wider, creating one column for each country. This is messy and difficult to interpret, so it was pivoted wider to list the countries under one "Country" column. 

After the untidying and retidying was done, some of the variables in the profile data set were separated into two variables. Some of the variables in this data set had two different numbers listed as one, such as the life expectancy at birth being listed as females/males. This variable cannot be interpreted for each gender since both values are listed as one, so it was separated into the life expectancy at birth for men and women separately, separating the values by the forward slash. This separation of variables was done for many that listed two different values as one, in order to create a tidier data set that can be interpreted more easily. 
    
#### Joining/Merging

```{R}
#re-coding variables
profile <- profile %>% mutate(country=case_when(country=="Russian Federation"~"Russia", country=="United States of America"~"United States", country=="China, Hong Kong SAR"~"Hong Kong S.A.R., China", country=="Bolivia (Plurinational State of)"~"Bolivia", country=="Venezuela (Bolivarian Republic of)"~"Venezuela", country=="Viet Nam"~"Vietnam", country=="Iran (Islamic Republic of)"~"Iran", country=="Czechia"~"Czech Republic", country=="Republic of Korea"~"South Korea", country=="Republic of Moldova"~"Moldova", country=="United Republic of Tanzania"~"Tanzania", country=="Democratic Republic of the Congo"~"Congo (Kinshasa)", country=="Congo"~"Congo (Brazzaville)", country=="Syrian Arab Republic"~"Syria",TRUE~country))
profile %>% head

profile %>% summarize(n_distinct(country))
happy %>% summarize(n_distinct(Country))

anti_join(happy, profile, by=c("Country"="country"))
anti_join(profile, happy, by=c("country"="Country"))
joined <- inner_join(happy, profile, by=c("Country"="country")) %>% select(Country, Region, everything())
joined %>% head
```

Before joining could be performed, it was noticed that the same countries are listed under different names in both data sets. Country names that were found to differ were changed in the profile data set to match the country names of the happy data set. For example, Russia is listed as "Russia" in the happy data set, but it is listed as "Russian Federation" in the profile data set, so it was changed to match the happy data set. An anti-join was used to easily identify and find which countries were listed under different names in order to change them. Once this process was complete, an inner join was performed to join both data sets by the country variable and exclude any rows with no matches. 

In the original profile data set there are 229 observations with 54 variables (columns), and in the happy data set, there are 155 observations with 12 variables (columns). All of the observations in both data sets are unique (229 and 155). After changing the country names so they matched eachother on both data sets, there are 6 countries in happy that are not in profile. Some of these are Taiwan Province of China, North Cyprus, and Kosovo. In profile, there are 80 countries not found in the happy data set. Some of these are Andorra, Bahamas, and Bermuda. Both data sets have 149 countries in common, so in the final joined data set there are 149 rows.

####  Wrangling

```{R}
joined <- joined %>% mutate(Country.size= ifelse(`Population in thousands (2017)`>mean(`Population in thousands (2017)`), "large", "small")) %>% mutate(HappyResult= ifelse(Happiness.Score>5, "Happy", "Sad"))
joined %>% select(1,4, 15,66:67)

joined %>% select(1:2, 66:67, 3:4, 15, 20, 27, 40:41, 46, 48, 53, 59) -> finaljoined

finaljoined %>% rename(pop=`Population in thousands (2017)`, GDP=`GDP per capita (current US$)`, unemployement=`Unemployment (% of labour force)`,  lifeex.f=Lifeexpectancy_females_yrs, lifeex.m=Lifeexpectancy_males_yrs, infmort=`Infant mortality rate (per 1000 live births`, physicians=`Health: Physicians (per 1000 pop.)`,seatswomen=`Seats held by women in national parliaments %`, co2=`CO2 emission estimates (million tons/tons per capita)`) -> finaljoined

finaljoined %>% mutate_at(9:15, as.numeric) ->finaljoined

finaljoined %>% na_if("...") %>% na_if("-99") %>% na_if("~0.0") -> finaljoined
```

Before wrangling my data, I created two categorical variables using "mutate". The first one is the country size based on population. A country is considered large if the population is above the average population in the data set, and it is considered small if it is below the average population in the data set. The second variable is the happiness result. If a country has a happiness score above 5 it is considered happy, but if it has a happiness score below 5, it is considered sad. I then narrowed down the columns from the joined data set so that I would only have 16 columns (variables) to work with for the remainder of the project. Many variables in the joined data set were listed as character type when they are actually numerical variables, so they were changed to numeric data using mutate_at. Finally, many observations had symbols or inconclusive outputs that were re-coded as NAs so the data would be uniform.


```{R}
finaljoined %>% na.omit() %>% summarize_if(is.numeric, mean) %>% pivot_longer(1:11, names_to="Variable", values_to="Mean")

finaljoined %>% group_by(Region) %>% summarize(mean_GDP=mean(GDP), sd_GDP=sd(GDP),mean_HappyScore=mean(Happiness.Score), sd_HappyScore=sd(Happiness.Score)) %>% arrange(desc(mean_HappyScore)) %>% kable(align="lcccc", caption="Summary Statistics of GDP and Happiness Score by Region")

finaljoined %>% na.omit() %>% filter(Region=="NorthernAmerica" | Region=="CentralAmerica" | Region=="SouthAmerica" | Region=="Caribbean") %>% summarize_if(is.numeric, list(median=median, max=max, min=min))

finaljoined %>% filter(str_detect(Region, "Europe")) %>% summarize_if(is.numeric, list(median=median, max=max, min=min)) %>% kable(caption="Summary Statistics of European countries")

finaljoined %>% group_by(Region, Country.size) %>% na.omit() %>% summarize(n=n(), max.happyscore=max(Happiness.Score), min.happyscore=min(Happiness.Score), max.co2=max(co2), min.co2=min(co2)) %>% arrange(desc(max.happyscore))

function1 <- function(x){100-x}
finaljoined %>% summarize(seatsmen=function1(seatswomen))
finaljoined %>% mutate(seatsmen=function1(seatswomen)) %>% select(1:13, 16, 14:15)

finaljoined %>% group_by(Region) %>% summarize(n=n()) %>% arrange(desc(n))
finaljoined %>% group_by(Country.size) %>% summarize(n=n()) %>% arrange(desc(n))
finaljoined %>% group_by(HappyResult) %>% summarize(n=n()) %>% arrange(desc(n))

finaljoined %>% summarize_all(function(x)sum(is.na(x))) %>% pivot_longer(1:15, names_to="variable", values_to="NAs") %>% arrange(desc(NAs))
```

First, the mean of all numerical variables was found to understand where most values fall in this data set. For example, the mean happiness score in this data set is 5.67, which means that on average, the countries are slightly above a score of 5, defining them as happy. Then, the standard deviation and mean of GDP and happiness score was calculated for each region in the data set and arranged by descending mean happiness score. Oceania is the region with the highest mean happiness score, and it also has a decently high GDP. The max, min, and median was then calculated for all of the countries in the Western hemisphere, and then for all European countries. The last table created gives the minimum and maximum happiness scores and CO2 emissions, grouping the countries by region and size. We can see that the country with the highest happiness score is a small country found in northern Europe, and the country with the lowest happiness score is a small country in western Asia. 


A function was used to create a column for the percentage of parliament seats held by men in each country, by subtracting the percentage of seats held by women from 100%. More summary statistics include the number of observations per category. The region with the most amount of countries in this data set is western Africa, and the region with the least amount of countries is southern Asia. There are 122 small countries and 27 large countries in this data set, and there are 94 happy countries and 55 sad countries. The physicians per 1000 people column has 46 NAs, and the unemployment rate, seats held by women, and CO2 emissions each have 1 NA value.

#### Visualizing

```{R}
finaljoined %>% ggplot(aes(Happiness.Score, GDP)) + geom_point() + geom_smooth(color="darkgray", method="lm", se=F) + facet_wrap(~Country.size) + ggtitle("GDP vs. Happiness Score based on Country Size") + scale_y_continuous(limits=c(0, 10000)) + labs(x= "Happiness Score")+ theme(plot.title = element_text(hjust = 0.5), panel.background = element_rect(fill = "lightblue", colour = "lightblue", size = 0.5, linetype = "solid"))
```

The plot above shows the relationship between the happiness score and GDP of the countries in the data set. This plot is faceted by the size of the country (small and large). As seen by the plot, there appears to be a positive relationship between GDP and the happiness score. As the GDP of a country increases, they have increasingly higher happiness scores. This relationship is present in both small and large countries, and there does not appear to be a significant difference in the relationship between GDP and happiness scores between small and large countries.

```{R}
finaljoined %>% ggplot(aes(Region, infmort)) + geom_bar(stat = "summary", fun =mean, fill = "lightseagreen") + geom_errorbar(stat="summary")+ theme(axis.text.x=element_text(angle = -90, hjust = 0)) + labs(title="Infant Mortality Rates by Region", x="Region", y="Infant Mortality Rate (per 1000 live births")+ theme(plot.title = element_text(hjust = 0.5))

```

The barplot above shows the average infant mortality rates for each region in the joined data set. As observed in the plot, the regions with the highest infant mortality rate are Middle Africa, Western Africa, and Eastern Africa. From the wrangling section, we learned that Middle Africa also had the lowest mean happiness score. The regions with the lowest infant mortality rate are Western Europe, Northern Europe, and Oceania. Western Europe and Oceania have some of the highest mean happiness scores. From these results, it can be inferred that there is an inverse relationship with happiness scores and infant mortality rates. The higher the infant mortality rate tends to be for a region, the lower the mean happiness score tends to be. It can also be observed that European regions tend to have the lowest infant mortality rates, and African regions tend to have the highest infant mortality rates. 

```{R}
finaljoined %>% ggplot(aes(x=HappyResult, y=unemployement)) + geom_boxplot() +
  geom_jitter(alpha=.6, aes(color=Country.size)) + scale_y_continuous(name = "Unemployment (% of labor force)", breaks=c(0, 5, 10, 15, 20, 25, 30), limits=c(0,30)) + labs(x= "Happy Result") + ggtitle("Percent of Unemployment by Result of Happiness Score")+ theme(plot.title = element_text(hjust = 0.5)) + theme_minimal()
```

This last plot shows the distribution of unemployment (by %), and it separates countries by if they're classified as "Happy" or "Sad". As seen in the graph, it seems that sad countries have slightly higher rates of unemployment, although the relationship is not that strong, since there is a lot of overall among the boxplots. The mean unemployment rate for sad countries is slightly above that of happy countries, but the upper quartile is clearly higher in the sad countries. Additionally, there are more outliers of countries that are classified as happy but have higher unemployment rates, but there is only one outlier for sad countries. From the graph it can also be seen that there is not any difference between small and large countries. They are distributed uniformly across unemployment rates and country size.

#### Concluding Remarks

After joining both data sets, computing summary statistics, and creating plots for various variables, we have seen that some of the predicted observations are true. Happiness scores do tend to be positively related to the GDP of each country, and it seems to be inversely related to unemployment rates (as unemployment increases, countries tend to be less happy). The effect of these variables on happiness does not have a different effect on small versus large countries, and the happiest countries in 2017 are mostly in Europe and the Americas.




